version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: your_database
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
